version: "3.5"

x-healthcheck: &basic_hc
  interval: 30s
  timeout: 20s
  retries: 3

services:
  # ────────── Metadata store ──────────
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.9
    command: >
      etcd
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls    http://0.0.0.0:2379
      --data-dir              /etcd
      --auto-compaction-mode  revision
      --auto-compaction-retention 1000
      --quota-backend-bytes   4294967296
      --snapshot-count        50000
    volumes:
      - etcd-data:/etcd
    healthcheck:
      <<: *basic_hc
      test: ["CMD", "etcdctl", "endpoint", "health"]

  # ────────── Object store ──────────
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER:     minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      <<: *basic_hc
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]

  # ────────── Vector DB ──────────
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.17
    command: ["milvus", "run", "standalone"]
    depends_on: [etcd, minio]
    environment:
      ETCD_ENDPOINTS:   etcd:2379
      MINIO_ADDRESS:    minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_USE_SSL:    "false"
    volumes:
      - milvus-data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      <<: *basic_hc
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
    restart: unless-stopped

volumes:
  etcd-data:
  minio-data:
  milvus-data:

networks:
  default:
    name: milvus
